// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package repo

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO "post" ("user_id", "title", "content")
VALUES ($1, $2, $3)
RETURNING id, user_id, title, content, created_at
`

type CreatePostParams struct {
	UserID  int32  `json:"user_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.UserID, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM "post"
WHERE "id" = $1 AND "user_id" = $2
`

type DeletePostParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.UserID)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, user_id, title, content, created_at FROM "post"
WHERE "id" = $1 LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listAllPosts = `-- name: ListAllPosts :many
SELECT id, user_id, title, content, created_at FROM "post"
ORDER BY "created_at" DESC
`

func (q *Queries) ListAllPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostContent = `-- name: UpdatePostContent :one
UPDATE "post"
SET "content" = $3
WHERE "id" = $1 AND "user_id" = $2
RETURNING id, user_id, title, content, created_at
`

type UpdatePostContentParams struct {
	ID      int32  `json:"id"`
	UserID  int32  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) UpdatePostContent(ctx context.Context, arg UpdatePostContentParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostContent, arg.ID, arg.UserID, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
