// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeletePost(ctx context.Context, arg DeletePostParams) error
	GetPostByID(ctx context.Context, id int32) (Post, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, userName string) (User, error)
	ListAllPosts(ctx context.Context) ([]Post, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	UpdatePostContent(ctx context.Context, arg UpdatePostContentParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
