version: '2'
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unused
    - misspell
    - goconst
issues:
  exclude-rules:
    - path: db/repo/.*
      linters:
        - errcheck
