
version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unused

issues:
  exclusions:
    rules:
      - path: db/repo/.*
        linters:
          - errcheck