version: "2" 

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unused

issues:
  rules:
    - path: db/repo/.*
      linters:
        - errcheck